spring.application.name=StudentCRUD1

spring.datasource.url=jdbc:mysql://localhost:3306/studentdb1
spring.datasource.username=root
spring.datasource.password=asha1606

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080